### ISSUE TITLE
Where I can find those python packages？

### ISSUE THREAD

**Issue by MichaelLiu-TJ** [MooreThreads/torch_musa#2]
Where I can find below python packages？
# for python3.8
pip install torch-2.0.0a0+gitc263bd4-cp38-cp38-linux_x86_64.whl
pip install torch_musa-2.0.0-cp38-cp38-linux_x86_64.whl

# for python3.9
pip install torch-2.0.0a0+gitc263bd4-cp39-cp39-linux_x86_64.whl
pip install torch_musa-2.0.0-cp39-cp39-linux_x86_64.whl

**Comment by mingyuanw-mt** [comment]
The whl packages are expected to be available this Friday. :-)

**Comment by lms-mt** [comment]
.whl packages released @MichaelLiu-TJ
