### ISSUE TITLE
No module named 'torchvision'

### ISSUE THREAD

**Issue by njnuko** [MooreThreads/torch_musa#29]
Docker环境下没法import torchvision
(py38) root@3cc6c4aed05b:/home# python
Python 3.8.17 (default, Jul  5 2023, 21:04:15)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch_musa
>>> import torchvision.models as models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torchvision'
>>>
===============================================
Docker 的命令
sudo docker run -it \
    --privileged \
    --name=torch_musa_release \
    --env MTHREADS_VISIBLE_DEVICES=all \
    -v /home/ko:/home \
    registry.mthreads.com/mcconline/musa-pytorch-release-public:latest /bin/bash
=================================================
宿主机上驱动版本
ko@home-pc:~/shell$ mthreads-gmi
Tue Mar 12 16:58:24 2024
---------------------------------------------------------------
    mthreads-gmi:1.8.2           Driver Version:2.5.0
---------------------------------------------------------------
ID   Name           |PCIe                |%GPU  Mem
     Device Type    |Pcie Lane Width     |Temp  MPC Capable
+-------------------------------------------------------------+
0    MTT S80        |00000000:26:00.0    |0%    37MiB(16384MiB)
     Physical       |16x(16x)            |45C   YES
---------------------------------------------------------------

---------------------------------------------------------------
Processes:
ID   PID       Process name                         GPU Memory
                                                         Usage
+-------------------------------------------------------------+
0    1057      /usr/lib/xorg/Xorg                        30MiB
0    1165      /usr/sbin/unity-greeter                   <1MiB
0    113489    python                                     2MiB
---------------------------------------------------------------
ko@home-pc:~/shell$

**Comment by chenfeng-mt** [comment]
把torchvision源码安装一下

**Comment by DonEvil1** [comment]
pip install --no-deps torchvision 试试

**Comment by MTwzx** [comment]
或者用"pip install --no-deps torchvision"试试

**Comment by njnuko** [comment]
已经按照官方手册装了1.5版本，可以用了，谢谢！
https://github.com/pytorch/vision/blob/main/CONTRIBUTING.md#development-installation
