### ISSUE TITLE
本地环境下安装torch_musa 1.1.0 版本报错 输入bash build.sh 时 pytorch 编译完毕，编译torch_musa 时出错

### ISSUE THREAD

**Issue by a1909095090** [MooreThreads/torch_musa#37]
-- Build files have been written to: /home/fei/torch_musa/build
cmake --build . --target install --config Release -- -j 12
[1/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub-RadixSortKeys.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub-RadixSortKeys.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub-RadixSortKeys.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/./musa_kernels_generated_cub-RadixSortKeys.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub-RadixSortKeys.mu.o.Release.cmake
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/musa/cub-RadixSortKeys.mu:3:
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/include/ATen/musa/cub.muh:11:
/home/fei/torch_musa/build/generated_cuda_compatible/include/ATen/musa/cub_definitions.muh:8:10: fatal error: 'cub/version.cuh' file not found
#include <cub/version.cuh>
         ^~~~~~~~~~~~~~~~~
1 error generated.
CMake Error at musa_kernels_generated_cub-RadixSortKeys.mu.o.Release.cmake:222 (message):
  Error generating
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/./musa_kernels_generated_cub-RadixSortKeys.mu.o

[2/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub-RadixSortPairs.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub-RadixSortPairs.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub-RadixSortPairs.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/./musa_kernels_generated_cub-RadixSortPairs.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub-RadixSortPairs.mu.o.Release.cmake
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/musa/cub-RadixSortPairs.mu:3:
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/include/ATen/musa/cub.muh:11:
/home/fei/torch_musa/build/generated_cuda_compatible/include/ATen/musa/cub_definitions.muh:8:10: fatal error: 'cub/version.cuh' file not found
#include <cub/version.cuh>
         ^~~~~~~~~~~~~~~~~
1 error generated.
CMake Error at musa_kernels_generated_cub-RadixSortPairs.mu.o.Release.cmake:222 (message):
  Error generating
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/./musa_kernels_generated_cub-RadixSortPairs.mu.o

[3/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/./musa_kernels_generated_cub.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/musa_kernels_generated_cub.mu.o.Release.cmake
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/musa/cub.mu:2:
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/include/ATen/musa/cub.muh:11:
/home/fei/torch_musa/build/generated_cuda_compatible/include/ATen/musa/cub_definitions.muh:8:10: fatal error: 'cub/version.cuh' file not found
#include <cub/version.cuh>
         ^~~~~~~~~~~~~~~~~
1 error generated.
CMake Error at musa_kernels_generated_cub.mu.o.Release.cmake:222 (message):
  Error generating
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/./musa_kernels_generated_cub.mu.o

[4/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardsigmoidKernel.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardsigmoidKernel.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardsigmoidKernel.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationHardsigmoidKernel.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardsigmoidKernel.mu.o.Release.cmake
/home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/native/musa/ActivationHardsigmoidKernel.mu:8:10: fatal error: 'thrust/tuple.h' file not found
#include <thrust/tuple.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
CMake Error at musa_kernels_generated_ActivationHardsigmoidKernel.mu.o.Release.cmake:222 (message):
  Error generating
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationHardsigmoidKernel.mu.o

[5/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_AbsKernel.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_AbsKernel.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_AbsKernel.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_AbsKernel.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_AbsKernel.mu.o.Release.cmake
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/native/musa/AbsKernel.mu:3:
/home/fei/torch_musa/build/generated_cuda_compatible/include/ATen/native/musa/Loops.muh:10:10: fatal error: 'thrust/tuple.h' file not found
#include <thrust/tuple.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
CMake Error at musa_kernels_generated_AbsKernel.mu.o.Release.cmake:222 (message):
  Error generating
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_AbsKernel.mu.o

[6/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardswishKernel.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardswishKernel.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardswishKernel.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationHardswishKernel.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardswishKernel.mu.o.Release.cmake
/home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/native/musa/ActivationHardswishKernel.mu:8:10: fatal error: 'thrust/tuple.h' file not found
#include <thrust/tuple.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
CMake Error at musa_kernels_generated_ActivationHardswishKernel.mu.o.Release.cmake:222 (message):
  Error generating
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationHardswishKernel.mu.o

[7/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationGeluKernel.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationGeluKernel.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationGeluKernel.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationGeluKernel.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationGeluKernel.mu.o.Release.cmake
/home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/native/musa/ActivationGeluKernel.mu:8:10: fatal error: 'thrust/tuple.h' file not found
#include <thrust/tuple.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
CMake Error at musa_kernels_generated_ActivationGeluKernel.mu.o.Release.cmake:222 (message):
  Error generating
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationGeluKernel.mu.o

[8/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationLeakyReluKernel.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationLeakyReluKernel.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationLeakyReluKernel.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationLeakyReluKernel.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationLeakyReluKernel.mu.o.Release.cmake
/home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/native/musa/ActivationLeakyReluKernel.mu:8:10: fatal error: 'thrust/tuple.h' file not found
#include <thrust/tuple.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
CMake Error at musa_kernels_generated_ActivationLeakyReluKernel.mu.o.Release.cmake:222 (message):
  Error generating
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationLeakyReluKernel.mu.o

[9/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardtanhKernel.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardtanhKernel.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardtanhKernel.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationHardtanhKernel.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationHardtanhKernel.mu.o.Release.cmake
/home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/native/musa/ActivationHardtanhKernel.mu:8:10: fatal error: 'thrust/tuple.h' file not found
#include <thrust/tuple.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
CMake Error at musa_kernels_generated_ActivationHardtanhKernel.mu.o.Release.cmake:222 (message):
  Error generating
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationHardtanhKernel.mu.o

[10/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationLogSigmoidKernel.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationLogSigmoidKernel.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationLogSigmoidKernel.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationLogSigmoidKernel.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationLogSigmoidKernel.mu.o.Release.cmake
/home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/native/musa/ActivationLogSigmoidKernel.mu:8:10: fatal error: 'thrust/tuple.h' file not found
#include <thrust/tuple.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
CMake Error at musa_kernels_generated_ActivationLogSigmoidKernel.mu.o.Release.cmake:222 (message):
  Error generating
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationLogSigmoidKernel.mu.o

[11/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationGluKernel.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationGluKernel.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationGluKernel.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationGluKernel.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/musa_kernels_generated_ActivationGluKernel.mu.o.Release.cmake
/home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/native/musa/ActivationGluKernel.mu:8:10: fatal error: 'thrust/tuple.h' file not found
#include <thrust/tuple.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
CMake Error at musa_kernels_generated_ActivationGluKernel.mu.o.Release.cmake:222 (message):
  Error generating
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/native/musa/./musa_kernels_generated_ActivationGluKernel.mu.o

[12/234] Building MCC (Device) object torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/detail/musa_kernels_generated_IndexUtils.mu.o
FAILED: torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/detail/musa_kernels_generated_IndexUtils.mu.o /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/detail/musa_kernels_generated_IndexUtils.mu.o 
cd /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/detail && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -E make_directory /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/detail/. && /home/fei/anaconda3/envs/py39/lib/python3.9/site-packages/cmake/data/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/detail/./musa_kernels_generated_IndexUtils.mu.o -P /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/detail/musa_kernels_generated_IndexUtils.mu.o.Release.cmake
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/aten/src/ATen/musa/detail/IndexUtils.mu:1:
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/include/ATen/musa/detail/IndexUtils.muh:3:
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/include/ATen/core/TensorBase.h:6:
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/include/c10/core/ScalarType.h:5:
In file included from /home/fei/torch_musa/build/generated_cuda_compatible/include/c10/util/Half.h:15:
/home/fei/torch_musa/build/generated_cuda_compatible/include/c10/util/complex.h:8:10: fatal error: 'thrust/complex.h' file not found
#include <thrust/complex.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated when compiling for mp_21.
CMake Error at musa_kernels_generated_IndexUtils.mu.o.Release.cmake:283 (message):
  Error generating file
  /home/fei/torch_musa/build/torch_musa/csrc/CMakeFiles/musa_kernels.dir/__/__/build/generated_cuda_compatible/aten/src/ATen/musa/detail/./musa_kernels_generated_IndexUtils.mu.o

ninja: build stopped: subcommand failed.
~/torch_musa
Please try the following commands once building torch_musa is failed: 
Clean PyTorch/torch_musa and build: 
cmd1: bash build.sh -c
If cmd1 still failed, update torch_musa to newest and build: 
cmd2: git fetch && git rebase origin/main && bash build.sh -c
If cmd2 still failed, update libraries and build: 
cmd3: bash docker/common/daily/update_daily_musart.sh && bash docker/common/daily/update_daily_mudnn.sh && bash build.sh -c
If cmd3 still failed, please check driver version on your host machine.

**Comment by hanhaowen-mt** [comment]
看上去是数学库没有安装，建议使用docker

**Comment by a1909095090** [comment]
谢谢&nbsp;
&nbsp;


1909095090
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月25日(星期一) 中午1:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MooreThreads/torch_musa] 本地环境下安装torch_musa 1.1.0 版本报错 输入bash build.sh 时 pytorch 编译完毕，编译torch_musa 时出错 (Issue #37)





 
看上去是数学库没有安装，建议使用docker
