### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by rhmaaa** [MooreThreads/torch_musa#49]
python
Python 3.8.19 (default, Mar 20 2024, 19:58:24) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vision/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/home/vision/torchvision/_meta_registrations.py", line 4, in <module>
    import torch._custom_ops
ModuleNotFoundError: No module named 'torch._custom_ops'

**Comment by rhmaaa** [comment]
解决了，建议在对应的torchvision安装的时候附上下图
![image](https://github.com/MooreThreads/torch_musa/assets/62527348/f9be9f53-7e40-4ad3-b3c4-7f05af32299f)

**Comment by RichardAwesome** [comment]
请问下可以告知如何解决的么，我git下载后安装的torchvision 的release/0.15的版本，依然无法成功导入该模块，感谢
