### ISSUE TITLE
能不能增加在wsl的使用

### ISSUE THREAD

**Issue by sorker** [MooreThreads/torch_musa#67]
如题。是否有大佬可以成功运行在wsl的Ubuntu中.

**Comment by wasong1** [comment]
wsl2是开启了虚拟化，目前MTT S80暂不支持虚拟化

**Comment by sorker** [comment]
> wsl2是开启了虚拟化，目前MTT S80暂不支持虚拟化
好的，谢谢答复。
期待将来能有这个能力
